"""
Crop profiles database module.
Provides research-backed environmental requirements, optimal and acceptable ranges,
seasonal windows, soil preferences, and authoritative source metadata (FAO ECOCROP, ICAR).
"""

from typing import Dict, Any, List, Optional, Tuple
from pydantic import BaseModel, Field


class CropRequirementProfile(BaseModel):
    crop: str
    display_name: str
    scientific_name: str
    ml_supported: bool
    category: str  # cereal, pulse, cash_crop, fruit, oilseed, vegetable
    seasons: List[str]  # kharif, rabi, zaid, annual
    temp_optimal: Tuple[float, float]  # Celsius (min, max)
    temp_acceptable: Tuple[float, float]
    rainfall_optimal: Tuple[float, float]  # mm per season (min, max)
    rainfall_acceptable: Tuple[float, float]
    humidity_optimal: Tuple[float, float]  # % (min, max)
    ph_optimal: Tuple[float, float]  # pH (min, max)
    ph_acceptable: Tuple[float, float]
    soil_textures: List[str]  # e.g., ["clay", "clay loam", "loam"]
    drainage: str  # well-drained, moderate, flooded
    soil_depth_min_cm: int
    water_requirement: str  # high, medium, low
    growth_duration_days: Tuple[int, int]
    regional_suitability: List[str]  # List of Indian states/regions or ["all"]
    source: str
    source_url: str
    notes: str


# Authoritative Crop Database (22 ML-supported + 4 catalogue expansion crops)
CROP_PROFILES: Dict[str, CropRequirementProfile] = {
    "rice": CropRequirementProfile(
        crop="rice",
        display_name="Rice (Paddy)",
        scientific_name="Oryza sativa",
        ml_supported=True,
        category="cereal",
        seasons=["kharif"],
        temp_optimal=(20.0, 35.0),
        temp_acceptable=(16.0, 38.0),
        rainfall_optimal=(1000.0, 2500.0),
        rainfall_acceptable=(800.0, 3000.0),
        humidity_optimal=(70.0, 90.0),
        ph_optimal=(5.5, 7.0),
        ph_acceptable=(4.5, 8.0),
        soil_textures=["clay", "clay loam", "silty clay loam", "loam"],
        drainage="flooded/poorly drained to moderate",
        soil_depth_min_cm=30,
        water_requirement="high",
        growth_duration_days=(120, 150),
        regional_suitability=["West Bengal", "Punjab", "Uttar Pradesh", "Andhra Pradesh", "Tamil Nadu", "Odisha", "Bihar", "Assam"],
        source="FAO ECOCROP & ICAR Rice Knowledge Management Portal",
        source_url="https://www.fao.org/land-water/databases-and-software/ecocrop",
        notes="High water requirements; thrives in flooded clay soils during Kharif season."
    ),
    "maize": CropRequirementProfile(
        crop="maize",
        display_name="Maize (Corn)",
        scientific_name="Zea mays",
        ml_supported=True,
        category="cereal",
        seasons=["kharif", "rabi"],
        temp_optimal=(18.0, 27.0),
        temp_acceptable=(12.0, 35.0),
        rainfall_optimal=(500.0, 800.0),
        rainfall_acceptable=(400.0, 1200.0),
        humidity_optimal=(55.0, 80.0),
        ph_optimal=(5.8, 7.2),
        ph_acceptable=(5.0, 8.0),
        soil_textures=["loam", "sandy loam", "clay loam", "silt loam"],
        drainage="well-drained",
        soil_depth_min_cm=45,
        water_requirement="medium",
        growth_duration_days=(90, 120),
        regional_suitability=["Karnataka", "Madhya Pradesh", "Maharashtra", "Rajasthan", "Bihar", "Telangana"],
        source="FAO ECOCROP & ICAR Indian Institute of Maize Research (IIMR)",
        source_url="https://iimr.icar.gov.in",
        notes="Sensitive to waterlogging; prefers well-drained fertile loamy soils."
    ),
    "jute": CropRequirementProfile(
        crop="jute",
        display_name="Jute",
        scientific_name="Corchorus capsularis",
        ml_supported=True,
        category="cash_crop",
        seasons=["kharif"],
        temp_optimal=(24.0, 38.0),
        temp_acceptable=(20.0, 40.0),
        rainfall_optimal=(1500.0, 2000.0),
        rainfall_acceptable=(1200.0, 2500.0),
        humidity_optimal=(75.0, 90.0),
        ph_optimal=(6.0, 7.5),
        ph_acceptable=(5.0, 8.0),
        soil_textures=["alluvial loam", "clay loam", "silt loam"],
        drainage="moderate",
        soil_depth_min_cm=30,
        water_requirement="high",
        growth_duration_days=(120, 150),
        regional_suitability=["West Bengal", "Assam", "Bihar", "Odisha", "Meghalaya"],
        source="FAO ECOCROP & ICAR Central Research Institute for Jute and Allied Fibres (CRIJAF)",
        source_url="http://www.crijaf.icar.gov.in",
        notes="Requires warm humid climate with ample rainfall during early growth."
    ),
    "cotton": CropRequirementProfile(
        crop="cotton",
        display_name="Cotton",
        scientific_name="Gossypium hirsutum",
        ml_supported=True,
        category="cash_crop",
        seasons=["kharif"],
        temp_optimal=(21.0, 32.0),
        temp_acceptable=(18.0, 38.0),
        rainfall_optimal=(600.0, 1100.0),
        rainfall_acceptable=(500.0, 1500.0),
        humidity_optimal=(50.0, 75.0),
        ph_optimal=(6.0, 8.0),
        ph_acceptable=(5.5, 8.5),
        soil_textures=["deep black clay (regur)", "clay loam", "loam"],
        drainage="well-drained",
        soil_depth_min_cm=60,
        water_requirement="medium",
        growth_duration_days=(150, 180),
        regional_suitability=["Gujarat", "Maharashtra", "Telangana", "Punjab", "Haryana", "Karnataka"],
        source="FAO ECOCROP & ICAR Central Institute for Cotton Research (CICR)",
        source_url="https://cicr.icar.gov.in",
        notes="Deep black soils retain moisture well for long cotton maturation."
    ),
    "wheat": CropRequirementProfile(
        crop="wheat",
        display_name="Wheat",
        scientific_name="Triticum aestivum",
        ml_supported=True,
        category="cereal",
        seasons=["rabi"],
        temp_optimal=(15.0, 25.0),
        temp_acceptable=(10.0, 30.0),
        rainfall_optimal=(450.0, 650.0),
        rainfall_acceptable=(350.0, 900.0),
        humidity_optimal=(50.0, 70.0),
        ph_optimal=(6.0, 7.5),
        ph_acceptable=(5.5, 8.2),
        soil_textures=["loam", "clay loam", "silt loam"],
        drainage="well-drained",
        soil_depth_min_cm=45,
        water_requirement="medium",
        growth_duration_days=(110, 140),
        regional_suitability=["Punjab", "Haryana", "Uttar Pradesh", "Madhya Pradesh", "Rajasthan", "Bihar"],
        source="FAO ECOCROP & ICAR Indian Institute of Wheat and Barley Research (IIWBR)",
        source_url="https://iiwbr.icar.gov.in",
        notes="Cool rabi crop requiring sunny dry harvest conditions."
    ),
    "chickpea": CropRequirementProfile(
        crop="chickpea",
        display_name="Chickpea (Gram)",
        scientific_name="Cicer arietinum",
        ml_supported=True,
        category="pulse",
        seasons=["rabi"],
        temp_optimal=(15.0, 25.0),
        temp_acceptable=(10.0, 30.0),
        rainfall_optimal=(400.0, 700.0),
        rainfall_acceptable=(300.0, 900.0),
        humidity_optimal=(40.0, 65.0),
        ph_optimal=(6.0, 7.8),
        ph_acceptable=(5.5, 8.5),
        soil_textures=["loam", "sandy loam", "clay loam"],
        drainage="well-drained",
        soil_depth_min_cm=30,
        water_requirement="low",
        growth_duration_days=(90, 120),
        regional_suitability=["Madhya Pradesh", "Maharashtra", "Rajasthan", "Karnataka", "Uttar Pradesh"],
        source="FAO ECOCROP & ICAR Indian Institute of Pulses Research (IIPR)",
        source_url="https://iipr.icar.gov.in",
        notes="Drought-tolerant leguminous crop; fixes atmospheric nitrogen."
    ),
    "kidneybeans": CropRequirementProfile(
        crop="kidneybeans",
        display_name="Kidney Beans (Rajma)",
        scientific_name="Phaseolus vulgaris",
        ml_supported=True,
        category="pulse",
        seasons=["rabi", "kharif"],
        temp_optimal=(18.0, 26.0),
        temp_acceptable=(14.0, 30.0),
        rainfall_optimal=(500.0, 800.0),
        rainfall_acceptable=(400.0, 1000.0),
        humidity_optimal=(50.0, 75.0),
        ph_optimal=(5.8, 6.8),
        ph_acceptable=(5.2, 7.5),
        soil_textures=["sandy loam", "loam", "silt loam"],
        drainage="well-drained",
        soil_depth_min_cm=30,
        water_requirement="medium",
        growth_duration_days=(85, 110),
        regional_suitability=["Himachal Pradesh", "Jammu & Kashmir", "Uttarakhand", "Maharashtra"],
        source="FAO ECOCROP & ICAR Pulses Division",
        source_url="https://iipr.icar.gov.in",
        notes="Prefers cool temperate conditions and fertile well-drained soils."
    ),
    "pigeonpeas": CropRequirementProfile(
        crop="pigeonpeas",
        display_name="Pigeon Peas (Arhar / Tur)",
        scientific_name="Cajanus cajan",
        ml_supported=True,
        category="pulse",
        seasons=["kharif"],
        temp_optimal=(20.0, 32.0),
        temp_acceptable=(16.0, 36.0),
        rainfall_optimal=(600.0, 1000.0),
        rainfall_acceptable=(500.0, 1300.0),
        humidity_optimal=(55.0, 75.0),
        ph_optimal=(6.0, 7.5),
        ph_acceptable=(5.0, 8.0),
        soil_textures=["deep loam", "sandy loam", "clay loam"],
        drainage="well-drained",
        soil_depth_min_cm=45,
        water_requirement="low",
        growth_duration_days=(150, 200),
        regional_suitability=["Maharashtra", "Karnataka", "Madhya Pradesh", "Gujarat", "Uttar Pradesh"],
        source="FAO ECOCROP & ICAR-IIPR",
        source_url="https://iipr.icar.gov.in",
        notes="Deep taproot makes it drought tolerant; often intercropped with cereals."
    ),
    "mothbeans": CropRequirementProfile(
        crop="mothbeans",
        display_name="Moth Beans",
        scientific_name="Vigna aconitifolia",
        ml_supported=True,
        category="pulse",
        seasons=["kharif", "zaid"],
        temp_optimal=(25.0, 35.0),
        temp_acceptable=(20.0, 42.0),
        rainfall_optimal=(300.0, 500.0),
        rainfall_acceptable=(200.0, 750.0),
        humidity_optimal=(40.0, 65.0),
        ph_optimal=(6.5, 8.0),
        ph_acceptable=(5.5, 8.5),
        soil_textures=["sandy", "sandy loam", "loam"],
        drainage="excessively drained",
        soil_depth_min_cm=20,
        water_requirement="low",
        growth_duration_days=(75, 90),
        regional_suitability=["Rajasthan", "Gujarat", "Haryana", "Punjab"],
        source="FAO ECOCROP & ICAR Central Arid Zone Research Institute (CAZRI)",
        source_url="http://www.cazri.res.in",
        notes="Extremely drought and heat tolerant pulse for arid regions."
    ),
    "mungbean": CropRequirementProfile(
        crop="mungbean",
        display_name="Mungbean (Green Gram)",
        scientific_name="Vigna radiata",
        ml_supported=True,
        category="pulse",
        seasons=["kharif", "zaid", "rabi"],
        temp_optimal=(25.0, 35.0),
        temp_acceptable=(20.0, 38.0),
        rainfall_optimal=(450.0, 750.0),
        rainfall_acceptable=(350.0, 950.0),
        humidity_optimal=(50.0, 75.0),
        ph_optimal=(6.2, 7.5),
        ph_acceptable=(5.5, 8.0),
        soil_textures=["loam", "sandy loam", "clay loam"],
        drainage="well-drained",
        soil_depth_min_cm=30,
        water_requirement="low",
        growth_duration_days=(60, 85),
        regional_suitability=["Rajasthan", "Maharashtra", "Karnataka", "Andhra Pradesh", "Odisha", "Punjab"],
        source="FAO ECOCROP & ICAR-IIPR",
        source_url="https://iipr.icar.gov.in",
        notes="Short-duration pulse ideal for crop rotation and summer sowing."
    ),
    "blackgram": CropRequirementProfile(
        crop="blackgram",
        display_name="Blackgram (Urad)",
        scientific_name="Vigna mungo",
        ml_supported=True,
        category="pulse",
        seasons=["kharif", "rabi", "zaid"],
        temp_optimal=(25.0, 35.0),
        temp_acceptable=(20.0, 38.0),
        rainfall_optimal=(500.0, 800.0),
        rainfall_acceptable=(400.0, 1000.0),
        humidity_optimal=(55.0, 80.0),
        ph_optimal=(6.0, 7.5),
        ph_acceptable=(5.5, 8.0),
        soil_textures=["loam", "clay loam", "sandy loam"],
        drainage="well-drained",
        soil_depth_min_cm=30,
        water_requirement="medium",
        growth_duration_days=(70, 95),
        regional_suitability=["Andhra Pradesh", "Maharashtra", "Madhya Pradesh", "Tamil Nadu", "Uttar Pradesh"],
        source="FAO ECOCROP & ICAR-IIPR",
        source_url="https://iipr.icar.gov.in",
        notes="Short duration legume grown across multiple seasons in warm areas."
    ),
    "lentil": CropRequirementProfile(
        crop="lentil",
        display_name="Lentil (Masoor)",
        scientific_name="Lens culinaris",
        ml_supported=True,
        category="pulse",
        seasons=["rabi"],
        temp_optimal=(15.0, 25.0),
        temp_acceptable=(10.0, 28.0),
        rainfall_optimal=(350.0, 600.0),
        rainfall_acceptable=(250.0, 800.0),
        humidity_optimal=(45.0, 65.0),
        ph_optimal=(6.0, 7.5),
        ph_acceptable=(5.5, 8.0),
        soil_textures=["loam", "silt loam", "clay loam"],
        drainage="well-drained",
        soil_depth_min_cm=30,
        water_requirement="low",
        growth_duration_days=(100, 130),
        regional_suitability=["Madhya Pradesh", "Uttar Pradesh", "Bihar", "West Bengal"],
        source="FAO ECOCROP & ICAR-IIPR",
        source_url="https://iipr.icar.gov.in",
        notes="Cool season pulse crop suited for residual moisture conditions."
    ),
    "pomegranate": CropRequirementProfile(
        crop="pomegranate",
        display_name="Pomegranate",
        scientific_name="Punica granatum",
        ml_supported=True,
        category="fruit",
        seasons=["annual"],
        temp_optimal=(25.0, 38.0),
        temp_acceptable=(15.0, 42.0),
        rainfall_optimal=(500.0, 800.0),
        rainfall_acceptable=(300.0, 1200.0),
        humidity_optimal=(40.0, 65.0),
        ph_optimal=(6.5, 7.8),
        ph_acceptable=(5.5, 8.5),
        soil_textures=["sandy loam", "loam", "clay loam"],
        drainage="well-drained",
        soil_depth_min_cm=60,
        water_requirement="medium",
        growth_duration_days=(180, 240),
        regional_suitability=["Maharashtra", "Karnataka", "Gujarat", "Andhra Pradesh", "Rajasthan"],
        source="FAO ECOCROP & ICAR National Research Centre on Pomegranate (NRCP)",
        source_url="https://nrcpomegranate.icar.gov.in",
        notes="Perennial fruit tree thriving in warm semi-arid climates."
    ),
    "banana": CropRequirementProfile(
        crop="banana",
        display_name="Banana",
        scientific_name="Musa acuminata",
        ml_supported=True,
        category="fruit",
        seasons=["annual"],
        temp_optimal=(22.0, 32.0),
        temp_acceptable=(15.0, 38.0),
        rainfall_optimal=(1500.0, 2500.0),
        rainfall_acceptable=(1000.0, 3000.0),
        humidity_optimal=(75.0, 90.0),
        ph_optimal=(6.0, 7.5),
        ph_acceptable=(5.5, 8.0),
        soil_textures=["rich clay loam", "alluvial loam", "silt loam"],
        drainage="well-drained with high organic matter",
        soil_depth_min_cm=80,
        water_requirement="high",
        growth_duration_days=(300, 365),
        regional_suitability=["Tamil Nadu", "Maharashtra", "Gujarat", "Andhra Pradesh", "Karnataka", "Kerala", "Assam"],
        source="FAO ECOCROP & ICAR National Research Centre for Banana (NRCB)",
        source_url="https://nrcb.icar.gov.in",
        notes="High water and nutrient requirement; sensitive to frost and strong winds."
    ),
    "mango": CropRequirementProfile(
        crop="mango",
        display_name="Mango",
        scientific_name="Mangifera indica",
        ml_supported=True,
        category="fruit",
        seasons=["annual"],
        temp_optimal=(24.0, 35.0),
        temp_acceptable=(18.0, 42.0),
        rainfall_optimal=(750.0, 1500.0),
        rainfall_acceptable=(500.0, 2500.0),
        humidity_optimal=(50.0, 75.0),
        ph_optimal=(5.5, 7.0),
        ph_acceptable=(4.5, 7.5),
        soil_textures=["deep alluvial loam", "lateritic clay loam", "loam"],
        drainage="well-drained",
        soil_depth_min_cm=100,
        water_requirement="medium",
        growth_duration_days=(300, 365),
        regional_suitability=["Uttar Pradesh", "Andhra Pradesh", "Karnataka", "Bihar", "Gujarat", "Maharashtra", "West Bengal"],
        source="FAO ECOCROP & ICAR Central Institute for Subtropical Horticulture (CISH)",
        source_url="https://cish.icar.gov.in",
        notes="Requires dry spell prior to flowering for good fruit set."
    ),
    "grapes": CropRequirementProfile(
        crop="grapes",
        display_name="Grapes",
        scientific_name="Vitis vinifera",
        ml_supported=True,
        category="fruit",
        seasons=["annual"],
        temp_optimal=(20.0, 32.0),
        temp_acceptable=(12.0, 38.0),
        rainfall_optimal=(500.0, 800.0),
        rainfall_acceptable=(400.0, 1000.0),
        humidity_optimal=(40.0, 65.0),
        ph_optimal=(6.5, 7.5),
        ph_acceptable=(5.5, 8.2),
        soil_textures=["sandy loam", "gravelly loam", "clay loam"],
        drainage="well-drained",
        soil_depth_min_cm=75,
        water_requirement="medium",
        growth_duration_days=(140, 180),
        regional_suitability=["Maharashtra", "Karnataka", "Tamil Nadu", "Andhra Pradesh", "Punjab"],
        source="FAO ECOCROP & ICAR National Research Centre for Grapes (NRCG)",
        source_url="https://nrcgrapes.icar.gov.in",
        notes="High humidity during ripening promotes fungal diseases."
    ),
    "watermelon": CropRequirementProfile(
        crop="watermelon",
        display_name="Watermelon",
        scientific_name="Citrullus lanatus",
        ml_supported=True,
        category="fruit",
        seasons=["zaid", "kharif"],
        temp_optimal=(24.0, 32.0),
        temp_acceptable=(18.0, 38.0),
        rainfall_optimal=(400.0, 600.0),
        rainfall_acceptable=(300.0, 800.0),
        humidity_optimal=(50.0, 70.0),
        ph_optimal=(6.0, 7.0),
        ph_acceptable=(5.5, 7.8),
        soil_textures=["sandy loam", "alluvial riverbed sand", "loam"],
        drainage="well-drained",
        soil_depth_min_cm=45,
        water_requirement="medium",
        growth_duration_days=(80, 100),
        regional_suitability=["Uttar Pradesh", "Karnataka", "Andhra Pradesh", "Tamil Nadu", "Maharashtra", "West Bengal"],
        source="FAO ECOCROP & ICAR Indian Institute of Horticultural Research (IIHR)",
        source_url="https://www.iihr.res.in",
        notes="Warm dry weather with abundant sunshine required during fruit development."
    ),
    "muskmelon": CropRequirementProfile(
        crop="muskmelon",
        display_name="Muskmelon",
        scientific_name="Cucumis melo",
        ml_supported=True,
        category="fruit",
        seasons=["zaid"],
        temp_optimal=(25.0, 34.0),
        temp_acceptable=(18.0, 38.0),
        rainfall_optimal=(350.0, 550.0),
        rainfall_acceptable=(250.0, 750.0),
        humidity_optimal=(45.0, 65.0),
        ph_optimal=(6.0, 7.2),
        ph_acceptable=(5.5, 7.8),
        soil_textures=["sandy loam", "riverbed loamy sand"],
        drainage="well-drained",
        soil_depth_min_cm=45,
        water_requirement="medium",
        growth_duration_days=(75, 95),
        regional_suitability=["Punjab", "Haryana", "Uttar Pradesh", "Rajasthan", "Madhya Pradesh"],
        source="FAO ECOCROP & ICAR-IIHR",
        source_url="https://www.iihr.res.in",
        notes="Requires hot dry climate during fruit ripening for sweetness accumulation."
    ),
    "apple": CropRequirementProfile(
        crop="apple",
        display_name="Apple",
        scientific_name="Malus domestica",
        ml_supported=True,
        category="fruit",
        seasons=["annual"],
        temp_optimal=(15.0, 24.0),
        temp_acceptable=(2.0, 28.0),
        rainfall_optimal=(1000.0, 1250.0),
        rainfall_acceptable=(800.0, 1500.0),
        humidity_optimal=(60.0, 80.0),
        ph_optimal=(5.8, 6.8),
        ph_acceptable=(5.5, 7.2),
        soil_textures=["loam", "silt loam", "sandy clay loam"],
        drainage="well-drained hill slope",
        soil_depth_min_cm=90,
        water_requirement="medium",
        growth_duration_days=(150, 210),
        regional_suitability=["Jammu & Kashmir", "Himachal Pradesh", "Uttarakhand"],
        source="FAO ECOCROP & ICAR Central Institute of Temperate Horticulture (CITH)",
        source_url="https://cith.icar.gov.in",
        notes="Temperate fruit requiring 800-1000 winter chilling hours below 7°C."
    ),
    "orange": CropRequirementProfile(
        crop="orange",
        display_name="Orange (Citrus)",
        scientific_name="Citrus sinensis",
        ml_supported=True,
        category="fruit",
        seasons=["annual"],
        temp_optimal=(20.0, 32.0),
        temp_acceptable=(10.0, 38.0),
        rainfall_optimal=(900.0, 1200.0),
        rainfall_acceptable=(600.0, 1500.0),
        humidity_optimal=(50.0, 75.0),
        ph_optimal=(6.0, 7.5),
        ph_acceptable=(5.5, 8.0),
        soil_textures=["deep loam", "sandy loam", "clay loam"],
        drainage="well-drained",
        soil_depth_min_cm=75,
        water_requirement="medium",
        growth_duration_days=(240, 300),
        regional_suitability=["Maharashtra (Nagpur)", "Punjab", "Rajasthan", "Assam", "Karnataka"],
        source="FAO ECOCROP & ICAR Central Citrus Research Institute (CCRI)",
        source_url="https://ccri.icar.gov.in",
        notes="Subtropical fruit preferring well-drained soils free of water stagnation."
    ),
    "papaya": CropRequirementProfile(
        crop="papaya",
        display_name="Papaya",
        scientific_name="Carica papaya",
        ml_supported=True,
        category="fruit",
        seasons=["annual"],
        temp_optimal=(22.0, 32.0),
        temp_acceptable=(16.0, 38.0),
        rainfall_optimal=(1200.0, 1800.0),
        rainfall_acceptable=(800.0, 2200.0),
        humidity_optimal=(65.0, 85.0),
        ph_optimal=(6.0, 7.0),
        ph_acceptable=(5.5, 7.5),
        soil_textures=["sandy loam", "rich alluvial loam"],
        drainage="exceptionally well-drained",
        soil_depth_min_cm=45,
        water_requirement="medium",
        growth_duration_days=(270, 330),
        regional_suitability=["Andhra Pradesh", "Gujarat", "Karnataka", "Madhya Pradesh", "Maharashtra", "West Bengal"],
        source="FAO ECOCROP & ICAR-IIHR",
        source_url="https://www.iihr.res.in",
        notes="Extremely sensitive to waterlogging (causes root rot within 48h)."
    ),
    "coconut": CropRequirementProfile(
        crop="coconut",
        display_name="Coconut",
        scientific_name="Cocos nucifera",
        ml_supported=True,
        category="fruit",
        seasons=["annual"],
        temp_optimal=(25.0, 32.0),
        temp_acceptable=(20.0, 36.0),
        rainfall_optimal=(1500.0, 2500.0),
        rainfall_acceptable=(1200.0, 3000.0),
        humidity_optimal=(75.0, 90.0),
        ph_optimal=(5.2, 8.0),
        ph_acceptable=(4.8, 8.5),
        soil_textures=["coastal sand", "alluvial loam", "laterite soil"],
        drainage="well-drained",
        soil_depth_min_cm=100,
        water_requirement="high",
        growth_duration_days=(365, 365),
        regional_suitability=["Kerala", "Tamil Nadu", "Karnataka", "Andhra Pradesh", "Odisha", "West Bengal", "Goa"],
        source="FAO ECOCROP & ICAR Central Plantation Crops Research Institute (CPCRI)",
        source_url="https://cpcri.icar.gov.in",
        notes="Tropical palm thriving in coastal humid zones with well-distributed rain."
    ),

    # Catalogue Expansion Crops (Non-ML supported)
    "mustard": CropRequirementProfile(
        crop="mustard",
        display_name="Mustard (Sarson)",
        scientific_name="Brassica juncea",
        ml_supported=False,
        category="oilseed",
        seasons=["rabi"],
        temp_optimal=(15.0, 25.0),
        temp_acceptable=(10.0, 30.0),
        rainfall_optimal=(300.0, 500.0),
        rainfall_acceptable=(200.0, 700.0),
        humidity_optimal=(45.0, 70.0),
        ph_optimal=(6.0, 7.5),
        ph_acceptable=(5.5, 8.2),
        soil_textures=["loam", "sandy loam", "clay loam"],
        drainage="well-drained",
        soil_depth_min_cm=30,
        water_requirement="low",
        growth_duration_days=(110, 135),
        regional_suitability=["Rajasthan", "Haryana", "Madhya Pradesh", "Uttar Pradesh", "West Bengal", "Punjab"],
        source="FAO ECOCROP & ICAR Directorate of Rapeseed-Mustard Research (DRMR)",
        source_url="https://drmr.icar.gov.in",
        notes="Major rabi oilseed requiring cool climate and light to medium loam soils."
    ),
    "sugarcane": CropRequirementProfile(
        crop="sugarcane",
        display_name="Sugarcane",
        scientific_name="Saccharum officinarum",
        ml_supported=False,
        category="cash_crop",
        seasons=["annual"],
        temp_optimal=(26.0, 35.0),
        temp_acceptable=(20.0, 38.0),
        rainfall_optimal=(1500.0, 2500.0),
        rainfall_acceptable=(1100.0, 3000.0),
        humidity_optimal=(60.0, 85.0),
        ph_optimal=(6.0, 7.5),
        ph_acceptable=(5.0, 8.5),
        soil_textures=["deep clay loam", "alluvial loam", "heavy clay"],
        drainage="well-drained with high moisture capacity",
        soil_depth_min_cm=60,
        water_requirement="high",
        growth_duration_days=(300, 365),
        regional_suitability=["Uttar Pradesh", "Maharashtra", "Karnataka", "Tamil Nadu", "Bihar", "Gujarat"],
        source="FAO ECOCROP & ICAR Sugarcane Breeding Institute (SBI)",
        source_url="https://sugarcane.icar.gov.in",
        notes="Long-duration crop requiring warm sunny conditions and copious irrigation."
    ),
    "potato": CropRequirementProfile(
        crop="potato",
        display_name="Potato",
        scientific_name="Solanum tuberosum",
        ml_supported=False,
        category="vegetable",
        seasons=["rabi"],
        temp_optimal=(15.0, 22.0),
        temp_acceptable=(10.0, 28.0),
        rainfall_optimal=(400.0, 600.0),
        rainfall_acceptable=(300.0, 800.0),
        humidity_optimal=(60.0, 80.0),
        ph_optimal=(5.2, 6.4),
        ph_acceptable=(4.8, 7.2),
        soil_textures=["sandy loam", "silt loam", "friable loam"],
        drainage="well-drained loose soil",
        soil_depth_min_cm=30,
        water_requirement="medium",
        growth_duration_days=(90, 115),
        regional_suitability=["Uttar Pradesh", "West Bengal", "Bihar", "Punjab", "Gujarat", "Madhya Pradesh"],
        source="FAO ECOCROP & ICAR Central Potato Research Institute (CPRI)",
        source_url="https://cpri.icar.gov.in",
        notes="Night temperatures above 20°C severely restrict tuberization."
    ),
    "groundnut": CropRequirementProfile(
        crop="groundnut",
        display_name="Groundnut (Peanut)",
        scientific_name="Arachis hypogaea",
        ml_supported=False,
        category="oilseed",
        seasons=["kharif", "rabi"],
        temp_optimal=(24.0, 30.0),
        temp_acceptable=(18.0, 35.0),
        rainfall_optimal=(500.0, 750.0),
        rainfall_acceptable=(400.0, 1000.0),
        humidity_optimal=(50.0, 75.0),
        ph_optimal=(6.0, 7.0),
        ph_acceptable=(5.5, 7.8),
        soil_textures=["sandy loam", "light loamy sand"],
        drainage="well-drained friable",
        soil_depth_min_cm=30,
        water_requirement="medium",
        growth_duration_days=(100, 130),
        regional_suitability=["Gujarat", "Andhra Pradesh", "Tamil Nadu", "Karnataka", "Rajasthan", "Maharashtra"],
        source="FAO ECOCROP & ICAR Directorate of Groundnut Research (DGR)",
        source_url="https://dgr.icar.gov.in",
        notes="Loose friable sandy loam essential for easy peg penetration and pod development."
    )
}


def get_crop_profile(crop_name: str) -> Optional[CropRequirementProfile]:
    """Retrieve crop requirement profile by key or display name (case-insensitive)."""
    key = crop_name.strip().lower()
    if key in CROP_PROFILES:
        return CROP_PROFILES[key]
    for profile in CROP_PROFILES.values():
        if profile.display_name.lower() == key or profile.scientific_name.lower() == key:
            return profile
    return None


def get_all_crop_profiles() -> List[CropRequirementProfile]:
    """Return all supported crop profiles in the agricultural catalogue."""
    return list(CROP_PROFILES.values())
